regex test passes, but the program doesn't quite work
TypeError: cannot concatenate str and NoneType objects (line 111) -- I
think you need to change the position of your question mark in your
opening brace regex so .group("code") can be the empty string